export interface LocalProduct {
  _id: string;
  name: string;
  price: number;
  description: string;
  category: string;
  collection: string;
  images: string[];
  colors: string[];
  sizes: string[];
  inStock: boolean;
  featured: boolean;
  stock: number;
  createdAt: string;
}

export const localProducts: LocalProduct[] = [

  // ── DARK CLOUD ──────────────────────────────────────────────────────────────
  {
    _id: 'dark-cloud-corset-maxi',
    name: 'Dark Cloud Corset Maxi',
    price: 15500,
    description: 'A showstopping strapless corset maxi in our Dark Cloud sunset-gradient print. Structured bodice meets floor-length drama — the kind of piece that commands every room.',
    category: 'Dress', collection: 'Dark Cloud',
    images: ['/products/dark-cloud-corset-maxi.jpg', '/products/dark-cloud-corset-maxi-1.jpg'],
    colors: ['Dark Cloud'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'dark-cloud-shirt',
    name: 'Dark Cloud Shirt',
    price: 7000,
    description: 'An oversized shirt in the Dark Cloud gradient — wear it open as a cover-up or buttoned as a statement. Effortless every time.',
    category: 'Top', collection: 'Dark Cloud',
    images: ['/products/dark-cloud-shirt.jpg', '/products/dark-cloud-shirt-1.jpg', '/products/dark-cloud-shirt-2.jpg'],
    colors: ['Dark Cloud'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 10, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'dark-cloud-waistcoat-dress',
    name: 'Dark Cloud Waistcoat Dress',
    price: 10500,
    description: 'A structured waistcoat reimagined as a mini dress with a dramatic tie belt. The Dark Cloud print makes this tailored silhouette feel electric.',
    category: 'Dress', collection: 'Dark Cloud',
    images: ['/products/dark-cloud-waistcoat-dress.jpg', '/products/dark-cloud-waistcoat-dress-1.jpg'],
    colors: ['Dark Cloud'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 6, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'dark-cloud-short-bodycon',
    name: 'Dark Cloud Short Bodycon',
    price: 8000,
    description: 'A sleek, form-fitting short bodycon dress in the Dark Cloud print. Minimal and powerful — your evenings just got more interesting.',
    category: 'Dress', collection: 'Dark Cloud',
    images: ['/products/dark-cloud-short-bodycon.jpg'],
    colors: ['Dark Cloud'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'dark-cloud-track-pants',
    name: 'Dark Cloud Track Pants',
    price: 10500,
    description: 'Wide-leg track pants with a side stripe detail in the Dark Cloud gradient print. The perfect blend of sporty and editorial.',
    category: 'Pants', collection: 'Dark Cloud',
    images: ['/products/dark-cloud-track-pants.jpg', '/products/dark-cloud-track-pants-1.jpg'],
    colors: ['Dark Cloud'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'dark-cloud-tieup-top',
    name: 'Dark Cloud Tie-up Top',
    price: 6500,
    description: 'A breezy tie-up top in the Dark Cloud sunset print. Knot it at the front or leave it loose — this one does all the work.',
    category: 'Top', collection: 'Dark Cloud',
    images: ['/products/dark-cloud-tieup-top.jpg', '/products/dark-cloud-tieup-top-1.jpg'],
    colors: ['Dark Cloud'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 12, createdAt: '2026-05-01T00:00:00.000Z',
  },

  // ── HORIZON ─────────────────────────────────────────────────────────────────
  {
    _id: 'horizon-scuba-maxi-cutout',
    name: 'Horizon Scuba Maxi with Cutout',
    price: 15500,
    description: 'A breathtaking ombré maxi with a sculptural cutout waist detail. The Horizon gradient — from sky blue to peach to deep ocean — renders each piece unique.',
    category: 'Dress', collection: 'Horizon',
    images: ['/products/horizon-scuba-maxi-cutout.jpg', '/products/horizon-scuba-maxi-cutout-1.jpg'],
    colors: ['Horizon'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 5, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'horizon-scuba-corset-dress',
    name: 'Horizon Scuba Corset Dress',
    price: 15500,
    description: 'The crown jewel of the Horizon collection — a structured corset dress with an embellished belt. Dramatic, sculpted, and completely one-of-a-kind.',
    category: 'Dress', collection: 'Horizon',
    images: ['/products/horizon-scuba-corset-dress.jpg', '/products/horizon-scuba-corset-dress-1.jpg'],
    colors: ['Horizon'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 4, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'horizon-combined-dress',
    name: 'Horizon Combined Dress',
    price: 12000,
    description: 'A masterful combination dress that plays with fabric and silhouette in the Horizon gradient. Where structure meets fluidity.',
    category: 'Dress', collection: 'Horizon',
    images: ['/products/horizon-combined-dress.jpg', '/products/horizon-combined-dress-1.jpg', '/products/horizon-combined-dress-2.jpg'],
    colors: ['Horizon'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 6, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'horizon-scuba-skirt',
    name: 'Horizon Scuba Skirt',
    price: 10500,
    description: 'A midi scuba skirt with scalloped pocket detail in the Horizon ombré. Elevated basics done the ARA way.',
    category: 'Skirt', collection: 'Horizon',
    images: ['/products/horizon-scuba-skirt.jpg'],
    colors: ['Horizon'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'horizon-bustier-top',
    name: 'Horizon Bustier Top',
    price: 10500,
    description: 'A structured bustier in the Horizon gradient. Wear it as a statement or layer it — either way, you are the look.',
    category: 'Top', collection: 'Horizon',
    images: ['/products/horizon-bustier-top.jpg', '/products/horizon-bustier-top-1.jpg'],
    colors: ['Horizon'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'horizon-scuba-track-pants',
    name: 'Horizon Scuba Track Pants',
    price: 10500,
    description: 'Wide-leg scuba track pants in the Horizon gradient. Sculptural and relaxed in equal measure.',
    category: 'Pants', collection: 'Horizon',
    images: ['/products/horizon-scuba-track-pants.jpg', '/products/horizon-scuba-track-pants-1.jpg'],
    colors: ['Horizon'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'horizon-poplin-shirt',
    name: 'Horizon Poplin Shirt',
    price: 7000,
    description: 'A relaxed poplin shirt in the Horizon gradient. A summer staple that looks just as good open over a swimsuit as it does buttoned up.',
    category: 'Top', collection: 'Horizon',
    images: ['/products/horizon-poplin-shirt.jpg', '/products/horizon-poplin-shirt-1.jpg', '/products/horizon-poplin-shirt-2.jpg'],
    colors: ['Horizon'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 10, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'horizon-poplin-skirt',
    name: 'Horizon Poplin Skirt',
    price: 8000,
    description: 'A crisp poplin midi skirt in the Horizon ombré. Clean lines, beautiful gradient — a wardrobe essential elevated.',
    category: 'Skirt', collection: 'Horizon',
    images: ['/products/horizon-poplin-skirt.jpg', '/products/horizon-poplin-skirt-1.jpg'],
    colors: ['Horizon'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 10, createdAt: '2026-05-01T00:00:00.000Z',
  },

  // ── OCEAN ────────────────────────────────────────────────────────────────────
  {
    _id: 'ocean-scuba-maxi-belt',
    name: 'Ocean Scuba Maxi with Belt',
    price: 15500,
    description: 'An ocean-toned scuba maxi cinched with a jewelled belt. Deep blues, aquas, and teals shift like the sea itself.',
    category: 'Dress', collection: 'Ocean',
    images: ['/products/ocean-scuba-maxi-belt.jpg', '/products/ocean-scuba-maxi-belt-1.jpg'],
    colors: ['Ocean'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 4, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'ocean-corset-dress',
    name: 'Ocean Corset Dress',
    price: 15500,
    description: 'A commanding corset dress with an embellished layered hem in Ocean tones. For the woman who makes a statement simply by walking in.',
    category: 'Dress', collection: 'Ocean',
    images: ['/products/ocean-corset-dress.jpg', '/products/ocean-corset-dress-1.jpg'],
    colors: ['Ocean'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 4, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'ocean-combined-maxi',
    name: 'Ocean Combined Maxi',
    price: 12000,
    description: 'A flowing combined maxi that blends two fabric stories in Ocean hues. Fluid, feminine, and deeply beautiful.',
    category: 'Dress', collection: 'Ocean',
    images: ['/products/ocean-combined-maxi.jpg', '/products/ocean-combined-maxi-1.jpg'],
    colors: ['Ocean'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 6, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'ocean-scuba-crop-top',
    name: 'Ocean Scuba Crop Top',
    price: 6500,
    description: 'A structured scuba crop top in Ocean gradient tones. Pair with the Ocean Skirt for a full look or style it your way.',
    category: 'Top', collection: 'Ocean',
    images: ['/products/ocean-scuba-crop-top.jpg', '/products/ocean-scuba-crop-top-1.jpg', '/products/ocean-scuba-crop-top-2.jpg'],
    colors: ['Ocean'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 10, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'ocean-scuba-pants',
    name: 'Ocean Scuba Pants',
    price: 9500,
    description: 'Wide-leg scuba pants in deep Ocean tones. Effortlessly elevated, perfect from brunch to evening.',
    category: 'Pants', collection: 'Ocean',
    images: ['/products/ocean-scuba-pants.jpg'],
    colors: ['Ocean'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },

  // ── BEACH ────────────────────────────────────────────────────────────────────
  {
    _id: 'beach-knotted-dress',
    name: 'Beach Knotted Dress',
    price: 8500,
    description: 'A sunny yellow midi dress with delicate hand-embroidered beach scene motifs and a knotted waist tie. The definition of effortless summer.',
    category: 'Dress', collection: 'Beach',
    images: ['/products/beach-knotted-dress.jpg', '/products/beach-knotted-dress-1.jpg'],
    colors: ['Sunshine Yellow'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'beach-mini-balloon-dress',
    name: 'Beach Mini Balloon Dress',
    price: 8500,
    description: 'A joyful mini balloon dress in sunshine yellow with playful hand-painted beach scenes. Puffed sleeves, drop hem — pure summer fun.',
    category: 'Dress', collection: 'Beach',
    images: ['/products/beach-mini-balloon-dress.jpg', '/products/beach-mini-balloon-dress-1.jpg'],
    colors: ['Sunshine Yellow'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'beach-crop-top',
    name: 'Beach Crop Top',
    price: 6500,
    description: 'A breezy beach crop in sunshine yellow. Simple, essential, and made for golden afternoons.',
    category: 'Top', collection: 'Beach',
    images: ['/products/beach-crop-top.jpg'],
    colors: ['Sunshine Yellow'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 12, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'beach-skort',
    name: 'Beach Skort',
    price: 8500,
    description: 'A sunny skort with hand-painted beach motifs — the perfect piece for days that go from shore to street.',
    category: 'Skirt', collection: 'Beach',
    images: ['/products/beach-skort.jpg'],
    colors: ['Sunshine Yellow'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 10, createdAt: '2026-05-01T00:00:00.000Z',
  },

  // ── WAVES ────────────────────────────────────────────────────────────────────
  {
    _id: 'waves-sun-dress',
    name: 'Waves Sun Dress',
    price: 7500,
    description: 'A halter-neck sun dress in sky-blue muslin with cloud and waves print. Light, airy, and utterly free — like a day without plans.',
    category: 'Dress', collection: 'Waves',
    images: ['/products/waves-sun-dress.jpg'],
    colors: ['Sky Blue'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 10, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'waves-scuba-frill-pants',
    name: 'Waves Scuba Frill Pants',
    price: 10000,
    description: 'Wide-leg scuba pants with a frill waist detail in the Waves cloud print. Dressed-up comfort for summer evenings.',
    category: 'Pants', collection: 'Waves',
    images: ['/products/waves-scuba-frill-pants.jpg', '/products/waves-scuba-frill-pants-1.jpg'],
    colors: ['Sky Blue'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'waves-scuba-top',
    name: 'Waves Scuba Top',
    price: 6000,
    description: 'A structured scuba top in the Waves cloud print. Wear it with the frill pants for a full look or mix and match.',
    category: 'Top', collection: 'Waves',
    images: ['/products/waves-scuba-top.jpg', '/products/waves-scuba-top-1.jpg'],
    colors: ['Sky Blue'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 12, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'waves-muslin-dress',
    name: 'Waves Muslin Dress',
    price: 7000,
    description: 'A flowy muslin dress in the Waves cloud print. Relaxed, romantic, and made for warm evenings.',
    category: 'Dress', collection: 'Waves',
    images: ['/products/waves-muslin-dress.jpg', '/products/waves-muslin-dress-1.jpg'],
    colors: ['Sky Blue'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 10, createdAt: '2026-05-01T00:00:00.000Z',
  },

  // ── PINK SKIES ───────────────────────────────────────────────────────────────
  {
    _id: 'pink-skies-corset-top',
    name: 'Pink Skies Corset Top',
    price: 10500,
    description: 'A structured corset top in the Pink Skies sunset print — bold pink with the drama of a dusk sky.',
    category: 'Top', collection: 'Pink Skies',
    images: ['/products/pink-skies-corset-top.jpg', '/products/pink-skies-corset-top-1.jpg'],
    colors: ['Pink Skies'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 6, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'pink-skies-bodycon-skirt',
    name: 'Pink Skies Bodycon Skirt',
    price: 10500,
    description: 'A body-hugging midi skirt in the Pink Skies gradient. Unexpected, striking, and completely ARA.',
    category: 'Skirt', collection: 'Pink Skies',
    images: ['/products/pink-skies-bodycon-skirt.jpg'],
    colors: ['Pink Skies'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 6, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'pink-skies-balloon-skirt',
    name: 'Pink Skies Balloon Skirt',
    price: 8000,
    description: 'A voluminous balloon skirt in the Pink Skies gradient. Playful, romantic, and impossible to ignore.',
    category: 'Skirt', collection: 'Pink Skies',
    images: ['/products/pink-skies-balloon-skirt.jpg', '/products/pink-skies-balloon-skirt-1.jpg'],
    colors: ['Pink Skies'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'pink-skies-tieup-top',
    name: 'Pink Skies Tie-up Top',
    price: 6500,
    description: 'A flirty tie-up top in the Pink Skies print. The easiest way to add a sunset to your look.',
    category: 'Top', collection: 'Pink Skies',
    images: ['/products/pink-skies-tieup-top.jpg'],
    colors: ['Pink Skies'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 12, createdAt: '2026-05-01T00:00:00.000Z',
  },

  // ── ORANGE VISTA ─────────────────────────────────────────────────────────────
  {
    _id: 'orange-vista-scuba-maxi',
    name: 'Orange Vista Scuba Maxi',
    price: 15500,
    description: 'A floor-length scuba maxi in the Orange Vista rainbow stripe print, cinched with a statement belt. The most beautiful garment in the room.',
    category: 'Dress', collection: 'Orange Vista',
    images: ['/products/orange-vista-scuba-maxi.jpg', '/products/orange-vista-scuba-maxi-1.jpg'],
    colors: ['Orange Vista'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 4, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'orange-vista-shirt',
    name: 'Orange Vista Shirt',
    price: 7000,
    description: 'An oversized shirt in the Orange Vista rainbow stripe — with a signature back bow tie detail.',
    category: 'Top', collection: 'Orange Vista',
    images: ['/products/orange-vista-shirt.jpg', '/products/orange-vista-shirt-1.jpg', '/products/orange-vista-shirt-2.jpg'],
    colors: ['Orange Vista'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: true, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'orange-vista-knotted-dress',
    name: 'Orange Vista Knotted Dress',
    price: 8500,
    description: 'A knotted midi dress in the Orange Vista rainbow print. Elegant and effortless — the ideal summer dress.',
    category: 'Dress', collection: 'Orange Vista',
    images: ['/products/orange-vista-knotted-dress.jpg'],
    colors: ['Orange Vista'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 6, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'orange-vista-scuba-skirt',
    name: 'Orange Vista Scuba Skirt',
    price: 10500,
    description: 'A tailored scuba midi skirt in Orange Vista hues. Structure meets colour in the most satisfying way.',
    category: 'Skirt', collection: 'Orange Vista',
    images: ['/products/orange-vista-scuba-skirt.jpg'],
    colors: ['Orange Vista'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 8, createdAt: '2026-05-01T00:00:00.000Z',
  },
  {
    _id: 'orange-vista-skort',
    name: 'Orange Vista Skort',
    price: 8500,
    description: 'A chic skort in the Orange Vista gradient — the versatile piece that works for everything.',
    category: 'Skirt', collection: 'Orange Vista',
    images: ['/products/orange-vista-skort.jpg'],
    colors: ['Orange Vista'], sizes: ['XS','S','M','L','XL'],
    inStock: true, featured: false, stock: 10, createdAt: '2026-05-01T00:00:00.000Z',
  },
];
